[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read-write", path = "./deployments/" }]
gas_price = 50000000000    # 50 gwei - very high for fast inclusion
priority_gas_price = 10000000000  # 10 gwei - very high priority fee for EIP-1559
gas_limit = 30000000       # High gas limit to avoid out-of-gas issues
solc = "0.8.20"

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/5NIZupGMAK990bNPC95clhTZBkvw4BrE"